require 'plugin_configs.colorscheme'
require 'plugin_configs.treesitter'
require 'plugin_configs.harpoon'
require 'plugin_configs.typescript'
require 'plugin_configs.cssls'
require 'plugin_configs.luasnip'
require 'plugin_configs.neotest-phpunit'
